name: projeto_integrador_iv
description: Aplicativo de Controle de Dispositivos IOT.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  auto_injector: ^1.0.2+2
  email_validator: ^2.1.17
  equatable: ^2.0.5
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.6+5
  flutter_svg: ^2.0.4
  go_router: ^6.4.1
  mask: ^1.0.4
  mobx: ^2.1.4
  result_dart: ^1.0.5
  sentry_flutter: ^7.2.0
  universal_html: ^2.2.1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  flutterando_analysis: ^0.0.2
  mobx_codegen: ^2.1.1
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
