name: projeto_integrador_iv
description: Aplicativo de Controle de Dispositivos IOT.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutterando_analysis: ^0.0.2

flutter:
  uses-material-design: true
